# This is a basic workflow to upload files 
# from GitHub to server via GitHub Actions
name: Publish Website on Vesta

# Controls when the workflow will run
on:

  # Triggers the workflow on push request event 
  # but only for the specific branch
  push:
    branches: [ main ]
  
  # Allows the workflow to be triggered manually
  workflow_dispatch:

# A workflow run is made up of one or more jobs 
# that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "SFTP-Deploy-Action"
  SFTP-Deploy-Action:
    name: Deploy to ${{ matrix.target }}

    # The type of runner that the job will run on 
    # (depends on server but usually this value works)
    runs-on: ubuntu-latest

    # Defines matrix of SFTP secrets for collaborators
    strategy:
      matrix:
        include:
          - target: epark06
            user-secret: FTP_USER
            pass-secret: FTP_PASSWORD
          - target: Jackbilsborrow
            user-secret: FTP_USER_J
            pass-secret: FTP_PASSWORD_J
          - target: RavencroftGM
            user-secret: FTP_USER_L
            pass-secret: FTP_PASSWORD_L
          - target: ismaix7
            user-secret: FTP_USER_I
            pass-secret: FTP_PASSWORD_I

    # Steps represent a sequence of tasks 
    # that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, 
      # so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        with:

          # Fetch all history for all tags and branches
          fetch-depth: 0

          # Checkout a specific branch
          ref: main

      # This is a composite GitHub Action (Linux runner) 
      # for deploying repository content to remote server
      - name: SFTP-Deploy-Action
        uses: pressidium/lftp-mirror-action@v1
        with: 
          # SFTP Creentials
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets[matrix.user-secret] }}
          pass: ${{ secrets[matrix.pass-secret] }}
          port: 22
          # lftp Settings
          onlyNewer: true
          settings: 'sftp:auto-confirm=yes'
          # Mirror command options
          localDir: '.'
          remoteDir: 'public_html/CO2007-assignment'